### ISSUE TITLE
Please add this to ultra prems

### ISSUE THREAD

**Issue by WesWesLabsYT** [TechsCode/PluginResources#90]
I have some ideas like adding different prefixes for the tab and the chat also I will like if you have name tag prefixes for the player's name.

**Comment by rlnt** [comment]
You already can add multiple prefixes to the tab menu and the chat.
Nameplate prefixes are not supported and never will be. Use another plugin for that.

This is not the place to submit issues or feature requests. This is just for adding new permissions and translations. If you have ideas or feature requests, join the discord or head to https://feedback.techsco.de/
